/* Formatted on 2016/01/29 12:18 (Formatter Plus v4.8.8) */
-- TABLESPACE DATA
DROP TABLESPACE "CDA_DAT" INCLUDING CONTENTS AND DATAFILES;
CREATE TABLESPACE "CDA_DAT" DATAFILE
  '/lundbprod/bdprod/oradata/SIDCA/CDA_DAT01.dbf' SIZE 1024 m AUTOEXTEND ON NEXT 256 m MAXSIZE 1024 m;

-- TABLESPACE INDEX
DROP TABLESPACE "CDA_IDX" INCLUDING CONTENTS AND DATAFILES;
CREATE TABLESPACE "CDA_IDX" DATAFILE
  '/lundbprod/bdprod/oradata/SIDCA/CDA_IDX01.dbf' SIZE 512 m AUTOEXTEND ON NEXT 100 m MAXSIZE 1024 m;
  
  ALTER TABLESPACE 
   "CDA_DAT" 
ADD DATAFILE 
   '/lundbprod/bdprod/oradata/SIDCA/CDA_DAT04.dbf' 
SIZE 2048 m AUTOEXTEND ON NEXT 200 m MAXSIZE 4096 m;

-- USER
DROP USER "CDA" CASCADE;
CREATE   USER "CDA" IDENTIFIED BY "cdaAPP" DEFAULT TABLESPACE "CDA_DAT" TEMPORARY TABLESPACE "TEMP" PROFILE DEFAULT ACCOUNT UNLOCK;

-- GRANT
GRANT "CONNECT" TO "CDA";
GRANT "RESOURCE" TO "CDA";
GRANT ALTER ANY INDEX TO "CDA";
GRANT ALTER ANY SEQUENCE TO "CDA";
GRANT ALTER ANY TABLE TO "CDA";
GRANT ALTER ANY TRIGGER TO "CDA";
GRANT CREATE ANY INDEX TO "CDA";
GRANT CREATE ANY SEQUENCE TO "CDA";
GRANT CREATE ANY SYNONYM TO "CDA";
GRANT CREATE ANY TABLE TO "CDA";
GRANT CREATE ANY TRIGGER TO "CDA";
GRANT CREATE ANY VIEW TO "CDA";
GRANT CREATE PROCEDURE TO "CDA";
GRANT CREATE PUBLIC SYNONYM TO "CDA";
GRANT CREATE TRIGGER TO "CDA";
GRANT CREATE VIEW TO "CDA";
GRANT DELETE ANY TABLE TO "CDA";
GRANT DROP ANY INDEX TO "CDA";
GRANT DROP ANY SEQUENCE TO "CDA";
GRANT DROP ANY TABLE TO "CDA";
GRANT DROP ANY TRIGGER TO "CDA";
GRANT DROP ANY VIEW TO "CDA";
GRANT INSERT ANY TABLE TO "CDA";
GRANT QUERY REWRITE TO "CDA";
GRANT SELECT ANY TABLE TO "CDA";
GRANT UNLIMITED TABLESPACE TO "CDA";